name: sgb-advisor

services:
    app:
        build: ./
        image: sgb_advisor:latest
        environment:
            MODE: both
        secrets:
            - API_KEYS
secrets:
    API_KEYS:
        file: .env
