---
name: Create docker image
permissions:
  contents: read
  packages: write
on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "src/"
      - ".dockerignore"
      - "Dockerfile"
      - ".github/workflows/create-docker-image.yaml"
      - ".python-version"
      - "requirements.txt"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Create and push the image
        env:
          GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
          GITHUB_REPOSITORY_OWNER: ${{ vars.GITHUB_REPOSITORY_OWNER }}
          GITHUB_SERVER_URL: ${{ vars.GITHUB_SERVER_URL }}
        run: |
          export GITHUB_REPOSITORY_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          export DOCKER_BUILD_GIT_COMMIT=`git rev-parse HEAD`
          export DOCKER_BUILD_SHORT_GIT_COMMIT=`git rev-parse --short HEAD`
          export DOCKER_BUILD_TIME=`date --rfc-3339=seconds`

          docker buildx build \
          --label "org.opencontainers.image.created=${DOCKER_BUILD_TIME}" \
          --label "org.opencontainers.image.version=${DOCKER_BUILD_GIT_COMMIT}" \
          --label "org.opencontainers.image.source=${GITHUB_REPOSITORY_URL}" \
          --tag "ghcr.io/${GITHUB_REPOSITORY}:latest" \
          --tag "ghcr.io/${GITHUB_REPOSITORY}:${DOCKER_BUILD_SHORT_GIT_COMMIT}" \
          --tag "ghcr.io/${GITHUB_REPOSITORY}:${DOCKER_BUILD_GIT_COMMIT}" \
          --file Dockerfile \
          .

          docker image ls --all

          docker push "ghcr.io/${GITHUB_REPOSITORY}:latest"
          docker push "ghcr.io/${GITHUB_REPOSITORY}:${DOCKER_BUILD_SHORT_GIT_COMMIT}"
          docker push "ghcr.io/${GITHUB_REPOSITORY}:${DOCKER_BUILD_GIT_COMMIT}"
