---
name: SGB Advisor
permissions:
  contents: none
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/sgb_advisor.yml"
      - "**.py"
      - "src/"
      - "requirements.txt"
      - ".python-version"
  # schedule:
  #   - cron: "30 4 * * 1-5" # Disabled till NSE allows foreign IPs again
  workflow_dispatch:

jobs:
  run-sgb-advisor:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo ⬇️
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup python and pip 🐍
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          cache: "pip" # caching pip dependencies
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Get playwright cache
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}-playwright
      - name: Setup and install playwright
        run: |
          playwright install --with-deps firefox
      - name: Run the script 🪙
        env:
          SGB_AWS_ACCESS_KEY: ${{ secrets.SGB_AWS_ACCESS_KEY }}
          SGB_AWS_SECRET_ACCESS_KEY: ${{ secrets.SGB_AWS_SECRET_ACCESS_KEY }}
          SGB_AWS_SES_RECIPIENT: ${{ secrets.SGB_AWS_SES_RECIPIENT }}
          SGB_AWS_SES_SENDER_EMAIL: ${{ secrets.SGB_AWS_SES_SENDER_EMAIL }}
          SGB_TELEGRAM_BOT_TOKEN: ${{ secrets.SGB_TELEGRAM_BOT_TOKEN }}
          SGB_TELEGRAM_CHAT_IDS: ${{ secrets.SGB_TELEGRAM_CHAT_IDS }}
          SGB_AWS_REGION: ${{ vars.SGB_AWS_REGION }}
          SGB_MODE: ${{ vars.SGB_MODE }}
          SGB_LOG_LEVEL: ${{ vars.SGB_LOG_LEVEL }}
        run: python3 -B app.py
